# Generated by Django 6.0.6 on 2026-06-28 11:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('wholesaleApp', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='areamaster',
            options={'ordering': ['city'], 'verbose_name': 'Area Master', 'verbose_name_plural': 'Area Masters'},
        ),
        migrations.RemoveField(
            model_name='areamaster',
            name='name',
        ),
    ]
