# Generated by Django 6.0.6 on 2026-07-06 03:57

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wholesaleApp', '0002_alter_areamaster_options_remove_areamaster_name'),
    ]

    operations = [
        migrations.CreateModel(
            name='SubareaMaster',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150, verbose_name='Subarea Name')),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('area', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='subareas', to='wholesaleApp.areamaster')),
            ],
            options={
                'verbose_name': 'Subarea Master',
                'verbose_name_plural': 'Subarea Masters',
                'ordering': ['name'],
            },
        ),
        migrations.AddField(
            model_name='customermaster',
            name='subarea',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='customers', to='wholesaleApp.subareamaster'),
        ),
    ]
