# Generated by Django 6.0.2 on 2026-07-06 05:22

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wholesaleApp', '0003_subareamaster_customermaster_subarea'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='CompanyMaster',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, unique=True, verbose_name='Company Name')),
                ('code', models.CharField(blank=True, max_length=50, null=True, verbose_name='Company Code')),
                ('status', models.BooleanField(default=True, verbose_name='Active')),
                ('is_deleted', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Company Master',
                'verbose_name_plural': 'Company Masters',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='DrugMaster',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, unique=True, verbose_name='Generic Composition')),
                ('status', models.BooleanField(default=True, verbose_name='Active')),
                ('is_deleted', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Drug Master',
                'verbose_name_plural': 'Drug Masters',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='ProductTypeMaster',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True, verbose_name='Product Type / Form')),
                ('status', models.BooleanField(default=True, verbose_name='Active')),
                ('is_deleted', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Product Type Master',
                'verbose_name_plural': 'Product Type Masters',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='ProductMaster',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='Brand Name')),
                ('pack_size', models.CharField(max_length=50, verbose_name='Packaging (e.g., 10 Tab, 100ml)')),
                ('hsn_code', models.CharField(blank=True, max_length=15, null=True, verbose_name='HSN Code')),
                ('gst_rate', models.DecimalField(decimal_places=2, default=12.0, max_digits=5, verbose_name='GST Rate (%)')),
                ('min_stock', models.IntegerField(default=10, verbose_name='Minimum Stock Level')),
                ('status', models.BooleanField(default=True, verbose_name='Active')),
                ('is_deleted', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='products', to='wholesaleApp.companymaster', verbose_name='Company')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('drug_composition', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='products', to='wholesaleApp.drugmaster', verbose_name='Drug Composition')),
                ('product_type', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='products', to='wholesaleApp.producttypemaster', verbose_name='Product Type')),
            ],
            options={
                'verbose_name': 'Product Master',
                'verbose_name_plural': 'Product Masters',
                'ordering': ['name'],
            },
        ),
    ]
