# Generated by Django 6.0.2 on 2026-07-13 16:46

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wholesaleApp', '0004_companymaster_drugmaster_producttypemaster_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='PurchaseEntry',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('invoice_number', models.CharField(max_length=100, verbose_name='Supplier Invoice No')),
                ('entry_date', models.DateField(auto_now_add=True, verbose_name='Date Recorded')),
                ('invoice_date', models.DateField(verbose_name='Invoice Date')),
                ('gross_amount', models.DecimalField(decimal_places=2, max_digits=12, verbose_name='Gross Amount (₹)')),
                ('discount_amount', models.DecimalField(decimal_places=2, default=0.0, max_digits=12, verbose_name='Discount (₹)')),
                ('gst_amount', models.DecimalField(decimal_places=2, max_digits=12, verbose_name='GST Amount (₹)')),
                ('net_amount', models.DecimalField(decimal_places=2, max_digits=12, verbose_name='Net Payable (₹)')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('supplier', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='purchase_entries', to='wholesaleApp.suppliermaster', verbose_name='Supplier')),
            ],
            options={
                'verbose_name': 'Purchase Entry',
                'verbose_name_plural': 'Purchase Entries',
                'ordering': ['-invoice_date', '-id'],
            },
        ),
        migrations.CreateModel(
            name='PurchaseEntryItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('batch_number', models.CharField(max_length=100, verbose_name='Batch Number')),
                ('expiry_date', models.DateField(verbose_name='Expiry Date')),
                ('mrp', models.DecimalField(decimal_places=2, max_digits=12, verbose_name='MRP (₹)')),
                ('purchase_rate', models.DecimalField(decimal_places=2, max_digits=12, verbose_name='Purchase Rate (₹)')),
                ('sale_rate', models.DecimalField(decimal_places=2, max_digits=12, verbose_name='Sale Rate (₹)')),
                ('quantity', models.IntegerField(verbose_name='Billed Qty (Packs)')),
                ('free_quantity', models.IntegerField(default=0, verbose_name='Free Qty')),
                ('discount_percentage', models.DecimalField(decimal_places=2, default=0.0, max_digits=5, verbose_name='Discount (%)')),
                ('total_amount', models.DecimalField(decimal_places=2, max_digits=12, verbose_name='Item Total (₹)')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='wholesaleApp.productmaster', verbose_name='Product')),
                ('purchase_entry', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='wholesaleApp.purchaseentry')),
            ],
        ),
        migrations.CreateModel(
            name='PurchaseOrder',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('po_number', models.CharField(max_length=50, unique=True, verbose_name='PO Number')),
                ('po_date', models.DateField(verbose_name='PO Date')),
                ('status', models.CharField(choices=[('Draft', 'Draft'), ('Sent', 'Sent'), ('Completed', 'Completed'), ('Cancelled', 'Cancelled')], default='Draft', max_length=20, verbose_name='Status')),
                ('net_amount', models.DecimalField(decimal_places=2, default=0.0, max_digits=12, verbose_name='Net Amount (₹)')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('supplier', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='purchase_orders', to='wholesaleApp.suppliermaster', verbose_name='Supplier')),
            ],
            options={
                'verbose_name': 'Purchase Order',
                'verbose_name_plural': 'Purchase Orders',
                'ordering': ['-po_date', '-id'],
            },
        ),
        migrations.CreateModel(
            name='PurchaseOrderItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.IntegerField(verbose_name='Ordered Qty (Packs)')),
                ('expected_rate', models.DecimalField(decimal_places=2, max_digits=12, verbose_name='Expected Purchase Rate (₹)')),
                ('total_amount', models.DecimalField(decimal_places=2, max_digits=12, verbose_name='Total (₹)')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='wholesaleApp.productmaster', verbose_name='Product')),
                ('purchase_order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='wholesaleApp.purchaseorder')),
            ],
        ),
        migrations.CreateModel(
            name='ProductBatch',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('batch_number', models.CharField(max_length=100, verbose_name='Batch Number')),
                ('expiry_date', models.DateField(verbose_name='Expiry Date')),
                ('mrp', models.DecimalField(decimal_places=2, max_digits=12, verbose_name='MRP (₹)')),
                ('purchase_rate', models.DecimalField(decimal_places=2, max_digits=12, verbose_name='Purchase Rate (₹)')),
                ('sale_rate', models.DecimalField(decimal_places=2, max_digits=12, verbose_name='Sale Rate (₹)')),
                ('quantity', models.IntegerField(default=0, verbose_name='Available Stock (Packs)')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='batches', to='wholesaleApp.productmaster', verbose_name='Product')),
            ],
            options={
                'verbose_name': 'Product Batch',
                'verbose_name_plural': 'Product Batches',
                'ordering': ['expiry_date', 'product__name'],
                'unique_together': {('product', 'batch_number', 'expiry_date', 'mrp', 'purchase_rate', 'sale_rate')},
            },
        ),
    ]
