# Generated by Django 6.0.2 on 2026-07-13 17:18

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wholesaleApp', '0005_purchaseentry_purchaseentryitem_purchaseorder_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='productmaster',
            name='scheme_free',
            field=models.IntegerField(default=0, verbose_name='Scheme Free Qty (e.g. 1)'),
        ),
        migrations.AddField(
            model_name='productmaster',
            name='scheme_qty',
            field=models.IntegerField(default=0, verbose_name='Scheme Billed Qty (e.g. 10)'),
        ),
        migrations.CreateModel(
            name='SalesInvoice',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('invoice_number', models.CharField(max_length=50, unique=True, verbose_name='Invoice Number')),
                ('invoice_date', models.DateField(verbose_name='Invoice Date')),
                ('gross_amount', models.DecimalField(decimal_places=2, max_digits=12, verbose_name='Gross Amount (₹)')),
                ('discount_amount', models.DecimalField(decimal_places=2, default=0.0, max_digits=12, verbose_name='Discount (₹)')),
                ('gst_amount', models.DecimalField(decimal_places=2, max_digits=12, verbose_name='GST Amount (₹)')),
                ('net_amount', models.DecimalField(decimal_places=2, max_digits=12, verbose_name='Net Amount Receivable (₹)')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('customer', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='sales_invoices', to='wholesaleApp.customermaster', verbose_name='Customer')),
            ],
            options={
                'verbose_name': 'Sales Invoice',
                'verbose_name_plural': 'Sales Invoices',
                'ordering': ['-invoice_date', '-id'],
            },
        ),
        migrations.CreateModel(
            name='SalesInvoiceItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.IntegerField(verbose_name='Billed Qty')),
                ('free_quantity', models.IntegerField(default=0, verbose_name='Free Qty')),
                ('sale_rate', models.DecimalField(decimal_places=2, max_digits=12, verbose_name='Selling Rate (₹)')),
                ('discount_percentage', models.DecimalField(decimal_places=2, default=0.0, max_digits=5, verbose_name='Discount (%)')),
                ('total_amount', models.DecimalField(decimal_places=2, max_digits=12, verbose_name='Item Total (₹)')),
                ('batch', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='wholesaleApp.productbatch', verbose_name='Batch')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='wholesaleApp.productmaster', verbose_name='Product')),
                ('sales_invoice', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='wholesaleApp.salesinvoice')),
            ],
        ),
    ]
