# Generated by Django 6.0.2 on 2026-07-13 17:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wholesaleApp', '0006_productmaster_scheme_free_productmaster_scheme_qty_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='salesinvoice',
            name='status',
            field=models.CharField(choices=[('Pending', 'Pending'), ('Delivered', 'Delivered'), ('Cancelled', 'Cancelled')], default='Pending', max_length=20, verbose_name='Delivery Status'),
        ),
    ]
