# Generated by Django 6.0.2 on 2026-07-13 18:21

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wholesaleApp', '0008_alter_salesinvoice_status'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='AppGroupModule',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True, verbose_name='Module Group Name')),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Module Group',
                'verbose_name_plural': 'Module Groups',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='AppFeature',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150, verbose_name='Feature Name')),
                ('codename', models.CharField(max_length=100, unique=True, verbose_name='System Codename')),
                ('is_active', models.BooleanField(default=True)),
                ('module', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='features', to='wholesaleApp.appgroupmodule')),
            ],
            options={
                'verbose_name': 'App Feature',
                'verbose_name_plural': 'App Features',
                'ordering': ['module__name', 'name'],
            },
        ),
        migrations.CreateModel(
            name='UserFeaturePermission',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_granted', models.BooleanField(default=False)),
                ('feature', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='wholesaleApp.appfeature')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='feature_permissions', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'User Feature Permission',
                'verbose_name_plural': 'User Feature Permissions',
                'unique_together': {('user', 'feature')},
            },
        ),
    ]
