# Generated by Django 6.0.2 on 2026-07-15 04:11

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wholesaleApp', '0010_userprofile'),
    ]

    operations = [
        migrations.CreateModel(
            name='Tenant',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True, verbose_name='Tenant Name')),
                ('company_name', models.CharField(max_length=200, verbose_name='Company Name')),
                ('address', models.TextField(blank=True, null=True)),
                ('phone', models.CharField(blank=True, max_length=20, null=True)),
                ('email', models.EmailField(blank=True, max_length=254, null=True)),
                ('gstin', models.CharField(blank=True, max_length=15, null=True, verbose_name='GSTIN')),
                ('dl_number', models.CharField(blank=True, max_length=50, null=True, verbose_name='Drug License Number')),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Tenant / Firm',
                'verbose_name_plural': 'Tenants / Firms',
            },
        ),
        migrations.AlterField(
            model_name='areamaster',
            name='code',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='companymaster',
            name='name',
            field=models.CharField(max_length=255, verbose_name='Company Name'),
        ),
        migrations.AlterField(
            model_name='customermaster',
            name='mobile',
            field=models.CharField(max_length=15),
        ),
        migrations.AlterField(
            model_name='drugmaster',
            name='name',
            field=models.CharField(max_length=255, verbose_name='Generic Composition'),
        ),
        migrations.AlterField(
            model_name='producttypemaster',
            name='name',
            field=models.CharField(max_length=100, verbose_name='Product Type / Form'),
        ),
        migrations.AlterField(
            model_name='purchaseorder',
            name='po_number',
            field=models.CharField(max_length=50, verbose_name='PO Number'),
        ),
        migrations.AlterField(
            model_name='salesinvoice',
            name='invoice_number',
            field=models.CharField(max_length=50, verbose_name='Invoice Number'),
        ),
        migrations.AlterField(
            model_name='suppliermaster',
            name='mobile',
            field=models.CharField(max_length=15),
        ),
        migrations.AddField(
            model_name='areamaster',
            name='tenant',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='%(class)s_records', to='wholesaleApp.tenant'),
        ),
        migrations.AddField(
            model_name='companymaster',
            name='tenant',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='%(class)s_records', to='wholesaleApp.tenant'),
        ),
        migrations.AddField(
            model_name='customermaster',
            name='tenant',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='%(class)s_records', to='wholesaleApp.tenant'),
        ),
        migrations.AddField(
            model_name='drugmaster',
            name='tenant',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='%(class)s_records', to='wholesaleApp.tenant'),
        ),
        migrations.AddField(
            model_name='productbatch',
            name='tenant',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='%(class)s_records', to='wholesaleApp.tenant'),
        ),
        migrations.AddField(
            model_name='productmaster',
            name='tenant',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='%(class)s_records', to='wholesaleApp.tenant'),
        ),
        migrations.AddField(
            model_name='producttypemaster',
            name='tenant',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='%(class)s_records', to='wholesaleApp.tenant'),
        ),
        migrations.AddField(
            model_name='purchaseentry',
            name='tenant',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='%(class)s_records', to='wholesaleApp.tenant'),
        ),
        migrations.AddField(
            model_name='purchaseentryitem',
            name='tenant',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='%(class)s_records', to='wholesaleApp.tenant'),
        ),
        migrations.AddField(
            model_name='purchaseorder',
            name='tenant',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='%(class)s_records', to='wholesaleApp.tenant'),
        ),
        migrations.AddField(
            model_name='purchaseorderitem',
            name='tenant',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='%(class)s_records', to='wholesaleApp.tenant'),
        ),
        migrations.AddField(
            model_name='salesinvoice',
            name='tenant',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='%(class)s_records', to='wholesaleApp.tenant'),
        ),
        migrations.AddField(
            model_name='salesinvoiceitem',
            name='tenant',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='%(class)s_records', to='wholesaleApp.tenant'),
        ),
        migrations.AddField(
            model_name='subareamaster',
            name='tenant',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='%(class)s_records', to='wholesaleApp.tenant'),
        ),
        migrations.AddField(
            model_name='suppliermaster',
            name='tenant',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='%(class)s_records', to='wholesaleApp.tenant'),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='tenant',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='user_profiles', to='wholesaleApp.tenant'),
        ),
        migrations.AlterUniqueTogether(
            name='areamaster',
            unique_together={('tenant', 'code')},
        ),
        migrations.AlterUniqueTogether(
            name='companymaster',
            unique_together={('tenant', 'name')},
        ),
        migrations.AlterUniqueTogether(
            name='customermaster',
            unique_together={('tenant', 'mobile')},
        ),
        migrations.AlterUniqueTogether(
            name='drugmaster',
            unique_together={('tenant', 'name')},
        ),
        migrations.AlterUniqueTogether(
            name='producttypemaster',
            unique_together={('tenant', 'name')},
        ),
        migrations.AlterUniqueTogether(
            name='purchaseorder',
            unique_together={('tenant', 'po_number')},
        ),
        migrations.AlterUniqueTogether(
            name='salesinvoice',
            unique_together={('tenant', 'invoice_number')},
        ),
        migrations.AlterUniqueTogether(
            name='suppliermaster',
            unique_together={('tenant', 'mobile')},
        ),
    ]
