# Generated by Django 6.0.2 on 2026-07-15 05:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wholesaleApp', '0011_tenant_alter_areamaster_code_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='customermaster',
            name='customer_type',
            field=models.CharField(choices=[('Retailer', 'Retailer / Chemist'), ('Wholesaler', 'Wholesaler / Sub-distributor')], default='Retailer', max_length=20, verbose_name='Customer Type'),
        ),
        migrations.AddField(
            model_name='productbatch',
            name='wholesale_rate',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=12, verbose_name='Wholesale Rate (₹)'),
        ),
        migrations.AddField(
            model_name='purchaseentryitem',
            name='wholesale_rate',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=12, verbose_name='Wholesale Rate (₹)'),
        ),
    ]
