# Generated by Django 6.0.2 on 2026-07-15 05:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wholesaleApp', '0012_customermaster_customer_type_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='purchaseentry',
            name='payment_type',
            field=models.CharField(choices=[('Cash', 'Cash'), ('Credit', 'Credit')], default='Credit', max_length=10, verbose_name='Payment Type'),
        ),
    ]
