# Generated by Django 6.0.6 on 2026-07-16 03:58

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wholesaleApp', '0013_purchaseentry_payment_type'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='salesinvoice',
            name='payment_type',
            field=models.CharField(choices=[('Cash', 'Cash'), ('Credit', 'Credit')], default='Cash', max_length=10, verbose_name='Payment Type'),
        ),
        migrations.CreateModel(
            name='CustomerPayment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('payment_date', models.DateField(verbose_name='Payment Date')),
                ('amount', models.DecimalField(decimal_places=2, max_digits=12, verbose_name='Amount Received (₹)')),
                ('payment_mode', models.CharField(choices=[('Cash', 'Cash'), ('Bank', 'Bank Transfer'), ('UPI', 'UPI'), ('Cheque', 'Cheque')], default='Cash', max_length=20, verbose_name='Payment Mode')),
                ('reference_no', models.CharField(blank=True, max_length=50, null=True, verbose_name='Ref / Trans No.')),
                ('remarks', models.TextField(blank=True, null=True, verbose_name='Remarks')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('customer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='payments', to='wholesaleApp.customermaster', verbose_name='Customer')),
                ('tenant', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='%(class)s_records', to='wholesaleApp.tenant')),
            ],
            options={
                'verbose_name': 'Customer Payment',
                'verbose_name_plural': 'Customer Payments',
                'ordering': ['-payment_date', '-id'],
            },
        ),
    ]
