# Generated by Django 6.0.2 on 2026-07-16 04:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wholesaleApp', '0014_salesinvoice_payment_type_customerpayment'),
    ]

    operations = [
        migrations.AlterField(
            model_name='salesinvoice',
            name='payment_type',
            field=models.CharField(choices=[('Cash', 'Cash'), ('Credit', 'Credit')], default='Credit', max_length=10, verbose_name='Payment Type'),
        ),
    ]
